### ISSUE TITLE
Complete all GET resquest for all classes

### ISSUE THREAD

**Issue by rog22rz** [ecse428-dream-team/ParkingBackEnd#8]

**Comment by rog22rz** [comment]
Also tried to add CORS support.

**Comment by ahmadowais123** [comment]
Did you get CORS to work? I was looking into it as well. Putting the @CrossOrigin annotation at the top of every controller seemed to do the trick. If yours works too I'm cool with it.

Something like this https://github.com/ecse428-dream-team/ParkingBackEnd/blob/a8cc23c3178070e157c90940df3e82b5b53efc5b/src/main/java/ca/mcgill/ecse428/parkingsystem/controller/ParkingManagerController.java#L14

**Comment by rog22rz** [comment]
Yeah I was looking at that method too. I think this works too, we can use it for the moment.
